# Generated by Django 4.2 on 2023-04-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseprediction',
            name='verification_token',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='diseaseprediction',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
