# Generated by Django 4.2 on 2023-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disease_detection", "0002_diseaseprediction_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseaseprediction",
            name="caution",
            field=models.TextField(default=""),
        ),
    ]
